apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - nodePort: {{ .Values.NodePort }}
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.name }}-deploy
  type: NodePort
